# Generated by Django 5.2.6 on 2026-07-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('apollo', 'Apollo.io'), ('snov', 'Snov.io'), ('prospeo', 'Prospeo.io'), ('reddit', 'Reddit Scraper'), ('gmaps', 'Google Maps Nursery Reviews'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('vetted', 'Vetted'), ('contacted', 'Contacted'), ('interested', 'Interested (Investor Opportunity)'), ('joined', 'Joined SEA Movement'), ('ignored', 'N/A / Wrong Fit')], default='discovered', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.lead')),
            ],
        ),
    ]
