# Generated by Django 5.2.6 on 2026-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='inclination_reasons',
            field=models.TextField(blank=True, help_text='Matched keywords or interest indicators', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='inclination_score',
            field=models.IntegerField(default=50, help_text='Estimated nature & sustainability inclination (0-100%)'),
        ),
    ]
