# Generated by Django 5.2.6 on 2026-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_inclination_reasons_lead_inclination_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='owner_username',
            field=models.CharField(db_index=True, default='admin', help_text='Username of account that owns this lead', max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='inclination_score',
            field=models.IntegerField(db_index=True, default=50, help_text='Estimated nature & sustainability inclination (0-100%)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('apollo', 'Apollo.io'), ('snov', 'Snov.io'), ('prospeo', 'Prospeo.io'), ('reddit', 'Reddit Scraper'), ('gmaps', 'Google Maps Nursery Reviews'), ('manual', 'Manual Entry')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('vetted', 'Vetted'), ('contacted', 'Contacted'), ('interested', 'Interested (Investor Opportunity)'), ('joined', 'Joined SEA Movement'), ('ignored', 'N/A / Wrong Fit')], db_index=True, default='discovered', max_length=20),
        ),
    ]
