# Generated by Django 5.2.6 on 2026-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_initial_verified_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=150)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('target_lead_id', models.IntegerField(blank=True, null=True)),
                ('target_lead_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetaTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=150, unique=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('last_device', models.CharField(blank=True, max_length=255, null=True)),
                ('last_action', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
