# Generated by Django 5.2.6 on 2026-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useractivitylog_usermetatracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetatracker',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
