# Generated by Django 5.2.6 on 2026-08-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_lead_owner_username_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(db_index=True, max_length=150)),
                ('title', models.CharField(help_text='Internal template name (e.g. Partnership Intro)', max_length=255)),
                ('subject', models.CharField(help_text='Email subject line supporting merge tags like {{ lead.name }}', max_length=255)),
                ('body_template', models.TextField(help_text='Email body template supporting {{ lead.name }}, {{ lead.organization }}, {{ sender_name }}')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(db_index=True, help_text='Username of account owning this email configuration', max_length=150)),
                ('sender_name', models.CharField(help_text='Display name for outgoing emails (e.g. SEA Movement Team)', max_length=255)),
                ('sender_email', models.EmailField(help_text='Organization email address', max_length=254)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP Host address', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP Port (e.g. 587 for TLS, 465 for SSL)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS connection')),
                ('smtp_username', models.CharField(help_text='SMTP Authentication Username (usually email address)', max_length=255)),
                ('smtp_app_password', models.CharField(help_text='16-character App Password or SMTP password', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(db_index=True, max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_logs', to='core.lead')),
            ],
        ),
    ]
